# -*- coding: utf-8 -*-
"""IntroduçãoBibliotecaPandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tuEyXIvSxuI7T8fq44dOp0uUXgtvFu9W
"""



from google.colab import drive
drive.mount('/content/drive')

import pandas as pds

df = pds.read_csv("/content/drive/MyDrive/datasets/Gapminder.csv", error_bad_lines = False, sep=";")

df.head()

df.rename(columns={"country":"pais"})

df.rename(columns={"continent":"continente"})

df.head(10)

df.shape

df.columns

df.dtypes

df.describe

df[continent].unique()

