# -*- coding: utf-8 -*-
"""PythonBásico.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hfKpGCLAnBz1xuqNcit_EjnOHfL9bZTv
"""

print("Olá Mundo!!")

print("Iniciando em Python")

"Estou aprendendo Python!"

1 + 1

10 - 2

#comentando em python

#multiplicação 2 * 2

#multiplicaçaõ
2 * 2

a = 4
b = 5
a * b

a/b

frase = "python para analise de dados"

print(frase)

frase[0]

frase{0:10}

frase[0:10]

frase.count(dados)

frase.count("dados")

frase.lower()

frase.upper()

tp = ("Banana", "Maça", 10, 58)

tp[0]

tp.count("Maça")

dc = { "Maça":10, "Banana":20}

dc["Maça"]

dc["Maça"] = 25

print(dc)

dc.keys()

dc.values()

dc.setdefault("Limão", 22)

print(dc)

