# -*- coding: utf-8 -*-
"""TrabalhandoComDatasEGraficos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iQfYlNyclTuuljNf8QwC8gcfDRa27uN1
"""

import pandas as pd 
import matplotlib.pyplot as plt
plt.style.use("seaborn")

from google.colab import files
arq = files.upload()

df = pd.read_excel("AdventureWorks.xlsx")

df.head(3)



df.shape

df.dtypes

df["Valor Venda"].sum()

df["Custo"] = df["Custo Unitário"].mul(df["Quantidade"]) #Criando a Coluna de Custos

df.head(1)

round(df["Custo"].sum(), 2)

#lucro total
df["Lucro"] = df["Valor Venda"] - df["Custo"]

df.head(1)

#lucro total
round(df["Lucro"].sum(), 2)

#total de dias de envio do produto
df["Tempo_envio"] = df["Data Envio"] - df["Data Venda"]

df.head(1)

#Extraindo apenas os dias
df["Tempo_envio"] = (df["Data Envio"] - df["Data Venda"]).dt.days

df.head(1)

#média do tempo de envio por marca
df.groupby("Marca")["Tempo_envio"].mean()

#verificando dados faltantes
df.isnull().sum()

#agrupando por ano e marca
df.groupby([df["Data Venda"].dt.year, "Marca"])["Lucro"].sum()

#tirando a notação cientifica
pd.options.display.float_format = '{:20,.2f}'.format

#resetando o index
lucro_ano = df.groupby([df["Data Venda"].dt.year, "Marca"])["Lucro"].sum().reset_index()

print(lucro_ano)

#total de produtos vendidos
df.groupby("Produto")["Quantidade"].sum().sort_values(ascending=False)

#grafico de produtos vendidos
df.groupby("Produto")["Quantidade"].sum().sort_values(ascending=True).plot.barh(title="Total Produtos Vendidos")
plt.xlabel("Total")
plt.ylabel("Produto");

#grafico de lucro por ano
df.groupby(df["Data Venda"].dt.year)["Lucro"].sum().plot.bar(title="lucro x ano")
plt.xlabel("Ano")
plt.ylabel("Receita");

df.groupby(df["Data Venda"].dt.year)["Lucro"].sum()

#apenas vendas de 2009
df_2009 = df[df["Data Venda"].dt.year == 2009]

df_2009.head()

print(df_2009)

#grafico de linha vendas 2009 por mes
df_2009.groupby(df_2009["Data Venda"].dt.month)["Lucro"].sum().plot(title="Lucro x Mês")
plt.xlabel("Mês")
plt.ylabel("Lucro");

#lucro por marca
df_2009.groupby("Marca")["Lucro"].sum().plot.bar(title="Lucro x Marca")
plt.xlabel("Marca")
plt.ylabel("Lucro")
plt.xticks(rotation="horizontal");

#lucro por classe
df_2009.groupby("Classe")["Lucro"].sum().plot.bar(title="Lucro x Classe")
plt.xlabel("Classe")
plt.ylabel("Lucro")
plt.xticks(rotation="horizontal");

df["Tempo_envio"].describe()

#gráfico de boxplot
plt.boxplot(df["Tempo_envio"]);

